# Generated by Django 5.0.4 on 2024-04-10 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sle', '0002_user_admission_type_user_batch_course_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registered_students',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
