# Generated by Django 5.0.4 on 2024-04-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sle', '0006_alter_course_elective_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
    ]
