# Generated by Django 5.0.4 on 2024-04-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sle', '0007_remove_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_created',
        ),
    ]
