# Generated by Django 5.0.4 on 2024-04-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sle', '0008_remove_course_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='elective_type',
            field=models.CharField(choices=[('Liberal Arts', 'LA'), ('Departmental Core Theory', 'DCT'), ('Departmental Core Lab', 'DCL'), ('Free Elective', 'FE'), ('Basic Science', 'BS'), ('Basic Engineering Skills', 'BES'), ('Additional', 'Additional'), ('Departmental Elective', 'DE')], default='LA', max_length=60),
        ),
    ]
