# Generated by Django 5.0.4 on 2024-04-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sle', '0009_alter_course_elective_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('news', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='admission_type',
            field=models.CharField(choices=[('regular', 'regular'), ('non-regular', 'distance')], default='regular', max_length=20),
        ),
    ]
